inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - lib/tasks/**

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*
